<!DOCTYPE HTML>
<html>
<head>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NKFL2BN');</script>
<!-- End Google Tag Manager -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width" />
<title>売却無料査定｜センチュリー21住宅セレクション: 神奈川エリアの不動産売買専門</title>
<meta name="Description" content="センチュリー21住宅セレクションの売却無料査定ページ" />
<meta name="Keywords" content="売却無料査定,センチュリー21住宅セレクション,神奈川県藤沢市,茅ヶ崎市,平塚市,寒川町,不動産,売買専門" />
<link rel="stylesheet" href="/css/style.css" />
<link rel="stylesheet" href="/css/form.css" />
<link rel="stylesheet" href="/assessment/contents.css" />
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
<!--&#91;if lt IE 9&#93;>
<script src="//cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
<!&#91;endif&#93;-->
<script src="https://code.jquery.com/jquery-latest.js"></script>
<script src="/js/common.js"></script>
<script type="text/javascript" src="//webfont.fontplus.jp/accessor/script/fontplus.js?KxqpanDaumc%3D&box=~8PqL6Bf2q8%3D&aa=1" charset="utf-8"></script>
<!---------------------
　スマホナビゲーション
----------------------->
<script type="text/javascript" src="/js/jquery.meanmenu.js"></script>
<link href="/css/meanmenu.css" rel="stylesheet" type="text/css">
<script>
(function($){
	$(function(){	
		$('#spheader').meanmenu({
			meanMenuClose: "x",
			meanMenuCloseSize: "18px",
			meanMenuOpen: "<span /><span /><span />",
			meanRevealPosition: "right",
			meanRevealColour: "",
			meanScreenWidth: "480"
		});
	});	
})(jQuery);
</script>
<!---------------------
　フォーム関連
----------------------->
<link rel="stylesheet" href="/css/inputchk.css" type="text/css" />
<script type="text/javascript" src="/js/inputchk.js"></script>
<!--送信チェック-->
<script type="text/javascript">
function sendMail() {
	var ret = checkSubmit();
	if (ret) {
		if(confirm("送信してもよろしいですか？")){
                        myFunction();
			return true;
		} else {
			return false;
		}
	}
	return ret;
}
</script>
<!--離脱アラート-->
<script>
jQuery(
 function($)
 {
	var loc=false;
     //store onbeforeunload for later use
   $(window).bind("beforeunload", function(e) {
 // 確認メッセージに表示させたい文字列を返します。
 if (!loc) {
 return "お問合せは完了しておりません。このページから移動してもよろしいですか？";
 }
});
//$('a').click( function() {loc=true;});
$("form").submit(function(){loc=true;});
 }
);
</script>
<!-------------------------------
toggle 表示・非表示
--------------------------------->
<script type="text/javascript">
	$(function(){
		
		//最初から非表示
		$('.pvbox').hide();
		$(".open").click(function(){
			$(this).next().slideToggle();
		});
	});
</script>

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5GPT3H');</script>
<!-- End Google Tag Manager -->
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '2805189076247155');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=2805189076247155&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->


<script type="text/javascript" src="//ajaxzip3.github.io/ajaxzip3.js" charset="utf-8"></script>




</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NKFL2BN"
                      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <div id="container">
        <?php include(__DIR__.'/../web/inc/header.inc'); ?>
        <?php include(__DIR__.'/../web/inc/nav.inc'); ?>
        <div id="contents">
            <div id="sptop" class="pchd">
                <a href="/loan_consultation/"><img src="/image/sptop.png" alt="住宅ローン審査の通過実績多数!! "></a>
            </div>
            <div id="assessment">
                <div class="inner">
                    <ol class="topicPath sphd">
                        <li><a href="/">センチュリー21 住宅セレクション</a></li>
                        <li>売却無料査定</li>
                    </ol>
                    <h1><i class="fas fa-calculator"></i>　売却無料査定</h1>
                    <div id="formWrap">
                        <div class="form-area">
                            
                            
                            <form id="mailform" method="post" action="/bin/common-contact.php?type=<?php echo $Param['type']; ?>">
                        <input type="hidden" id="type" name="type" value="<?php echo $Param['type']; ?>" />
                        <input type="hidden" id="mode" name="mode" value="reg" />
                        <?php echo $hidden_html; ?>
                                
                                <!-- タイトルが必要な場合は以下のhidden属性の「value」に入力 -->
                                <h2>お問い合わせ内容</h2>
                                <table class="fbox"summary="お問い合わせ内容" width="100%" border="0" cellspacing="0" cellpadding="0">

                                    <tr>
                                        <th><div class="anq_required">査定希望物件の種別</div></th>
                                        <td colspan="2"><?php echo $Param["kibo_type_text"];?><?php echo $err_kibo_type; ?></td>
                                    </tr>


                                    <tr>
                                        <th>築年</th>
                                        <td colspan="2"><?php echo $Param["chikunen_text"];?></td>
                                    </tr>
                                    <tr>
                                        <th>間取り</th>
                                        <td colspan="2"><?php echo $Param["madori_text"];?></td>
                                    </tr>
                                    <tr>
                                        <th>土地面積</th>
                                        <td colspan="2"><?php echo $Param["land_area_text"];?></td>
                                    </tr>
                                    <tr>
                                        <th>建物面積</th>
                                        <td colspan="2"><?php echo $Param["bld_area_text"];?></td>
                                    </tr>
                                    <tr>
                                        <th>専有面積など</th>
                                        <td colspan="2"><?php echo $Param["senyu_area_text"];?></td>
                                    </tr>


                                    <tr>
                                        <th><div class="anq_required">物件所在地</div></th>
                                        <td colspan="2"><?php echo $Param["shozaichi"];?><?php echo $err_shozaichi; ?></td>
                                    </tr>

                                    <tr>
                                        <th>ご希望売却価格</th>
                                        <td colspan="2"><?php echo ($Param["kibo_price"] != "") ? $Param["kibo_price"]."万円くらい" : "";?></td>
                                    </tr>

                                    <tr>
                                        <!--<th>ご売却又は買替え動機</th>-->
                                        <th>ご売却について</th>
                                        <td colspan="2"><?php echo nl2br($Param["douki"]);?></td>
                                    </tr>

                                    <tr>
                                        <th>売却予定時期</th>
                                        <td colspan="2"><?php echo $Param["kibo_time"];?></td>
                                    </tr>

                                    <tr>
                                        <th>正確な査定を希望する</th>
                                        <td colspan="2"><?php echo $Param["correct_kibo"];?></td>
                                    </tr>
                                </table>

                                <!------------------------------------------------------------------------
                                -------------------------------------------------------------------------->

                                <h2>お客様情報</h2>
                                <?php include(__DIR__ . '/form_parts/kokyaku_confirm.inc'); ?>

                                <div id="privacy">
                                    <p class="open">弊社の<span>プライバシーポリシー</span>をお読みいただき、すべての内容に同意のうえご登録ください。</p>
                                    <?php include(__DIR__ . '/form_parts/privacy_policy.inc'); ?>
                                    <!--/privacy-->
                                </div>

                                <div id="submit">
                                    <input type="button" value="修正する" class="css_btn_class2 maru" onclick="history.back();">
                                    <?php if (empty($err)) { ?><input type="submit" value="送信する" class="css_btn_class maru"><?php } ?>
                                </div>
                            </form>
                        </div>
                        <!--formWrap-->
                    </div>


                    <!--/inner-->
                </div>
                <!--/assessment-->
            </div>
            <!--/contents-->
        </div>

        <?php include(__DIR__.'/../web/inc/footerbanner.inc'); ?>
        <?php include(__DIR__.'/../web/inc/footer.inc'); ?>
    </div>
    <p class="pagetop"><a href="#container">▲</a></p>
    
    <?php include(__DIR__.'/../web/inc/sidebt.inc'); ?>
    <?php include(__DIR__.'/../web/inc/footbt.inc'); ?>
</body>
</html>
