<!DOCTYPE HTML>
<html>
<head>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NKFL2BN');</script>
<!-- End Google Tag Manager -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width" />
<title>売却無料査定｜センチュリー21住宅セレクション: 神奈川エリアの不動産売買専門</title>
<meta name="Description" content="センチュリー21住宅セレクションの売却無料査定ページ" />
<meta name="Keywords" content="売却無料査定,センチュリー21住宅セレクション,神奈川県藤沢市,茅ヶ崎市,平塚市,寒川町,不動産,売買専門" />
<link rel="stylesheet" href="/css/style.css" />
<link rel="stylesheet" href="/css/form.css" />
<link rel="stylesheet" href="/assessment/contents.css" />
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
<!--&#91;if lt IE 9&#93;>
<script src="//cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
<!&#91;endif&#93;-->
<script src="https://code.jquery.com/jquery-latest.js"></script>
<script src="/js/common.js"></script>
<script type="text/javascript" src="//webfont.fontplus.jp/accessor/script/fontplus.js?KxqpanDaumc%3D&box=~8PqL6Bf2q8%3D&aa=1" charset="utf-8"></script>
<!---------------------
　スマホナビゲーション
----------------------->
<script type="text/javascript" src="/js/jquery.meanmenu.js"></script>
<link href="/css/meanmenu.css" rel="stylesheet" type="text/css">
<script>
(function($){
	$(function(){	
		$('#spheader').meanmenu({
			meanMenuClose: "x",
			meanMenuCloseSize: "18px",
			meanMenuOpen: "<span /><span /><span />",
			meanRevealPosition: "right",
			meanRevealColour: "",
			meanScreenWidth: "480"
		});
	});	
})(jQuery);
</script>
<!---------------------
　フォーム関連
----------------------->
<link rel="stylesheet" href="/css/inputchk.css" type="text/css" />
<script type="text/javascript" src="/js/inputchk.js"></script>
<!--送信チェック-->
<script type="text/javascript">
function sendMail() {
	var ret = checkSubmit();
	if (ret) {
		if(confirm("送信してもよろしいですか？")){
                        myFunction();
			return true;
		} else {
			return false;
		}
	}
	return ret;
}
</script>
<!--離脱アラート-->
<script>
jQuery(
 function($)
 {
	var loc=false;
     //store onbeforeunload for later use
   $(window).bind("beforeunload", function(e) {
 // 確認メッセージに表示させたい文字列を返します。
 if (!loc) {
 return "お問合せは完了しておりません。このページから移動してもよろしいですか？";
 }
});
//$('a').click( function() {loc=true;});
$("form").submit(function(){loc=true;});
 }
);
</script>
<!-------------------------------
toggle 表示・非表示
--------------------------------->
<script type="text/javascript">
	$(function(){
		
		//最初から非表示
		$('.pvbox').hide();
		$(".open").click(function(){
			$(this).next().slideToggle();
		});
	});
</script>

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5GPT3H');</script>
<!-- End Google Tag Manager -->
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '2805189076247155');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=2805189076247155&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->


<script type="text/javascript" src="//ajaxzip3.github.io/ajaxzip3.js" charset="utf-8"></script>


<script type="text/javascript">
    function myFunction() {
        var post_data = {};
        
        var name = $("#kokyaku_nameID").val();
        var email = $("#mail_addr1ID").val();
        
        $zoho.salesiq.visitor.name(name);
        $zoho.salesiq.visitor.email(email);
    }
</script>



</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NKFL2BN"
                      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <div id="container">
        <?php include(__DIR__.'/../web/inc/header.inc'); ?>
        <?php include(__DIR__.'/../web/inc/nav.inc'); ?>
        <div id="contents">
            <div id="sptop" class="pchd">
                <a href="/loan_consultation/"><img src="/image/sptop.png" alt="住宅ローン審査の通過実績多数!! "></a>
            </div>
            <div id="assessment">
                <div class="inner">
                    <ol class="topicPath sphd">
                        <li><a href="/">センチュリー21 住宅セレクション</a></li>
                        <li>売却無料査定</li>
                    </ol>
                    <h1><i class="fas fa-calculator"></i>　売却無料査定</h1>
                    <div id="formWrap">
                        <div class="form-area">
                            
                            
                            <form id="mailform" method="post" action="/bin/common-contact.php">
                                <input type="hidden" id="type" name="type" value="assessment" />
                                <input type="hidden" id="mode" name="mode" value="confirm" />
                                <?php echo $hidden_html; ?>
                                
                                <!-- タイトルが必要な場合は以下のhidden属性の「value」に入力 -->
                                <h2>お問い合わせ内容</h2>
                                <table class="fbox"summary="お問い合わせ内容" width="100%" border="0" cellspacing="0" cellpadding="0">

                                    <tr>
                                        <th><div class="anq_required">査定希望物件の種別<span class="must">必須</span></div></th>
                                        <td colspan="2">
                                            <ul class="tate">
                                                <li>
                                                    <input type="radio" name="kibo_type" siqatrib="kibo_type" data-dispname="査定希望物件の種別" id="radio1_1" data-group="hisu1" class="chk_input chk_required" value="一戸建" />
                                                    <label for="radio1_1" class="radio">一戸建</label>
                                                </li>

                                                <li>
                                                    <input type="radio" name="kibo_type" siqatrib="kibo_type" data-dispname="査定希望物件の種別" id="radio1_2" data-group="hisu1" class="chk_input chk_required" value="土地" />
                                                    <label for="radio1_2" class="radio_in">土地（現況 :　

                                                        <input name="kibo_type_genkyo1" data-dispname="査定希望物件の種別／土地（現況 : " data-group="hisu1" id="checkbox1" class="chk_input" type="checkbox" value="現況(更地)" />
                                                        <label for="checkbox1" class="checkbox_in">更地</label>

                                                        <input name="kibo_type_genkyo2" data-dispname="査定希望物件の種別／土地（現況 : " data-group="hisu1" id="checkbox2" class="chk_input" type="checkbox" value="現況(古家あり)" />
                                                        <label for="checkbox2" class="checkbox_in">現況(古家あり)</label>
                                                    </label></li>

                                                <li>
                                                    <input type="radio" name="kibo_type" siqatrib="kibo_type" data-dispname="査定希望物件の種別" id="radio1_3" data-group="hisu1" class="chk_input chk_required" value="マンション" />
                                                    <label for="radio1_3" class="radio">マンション（名称 : 

                                                        <input name="kibo_mansion_name" siqatrib="kibo_mansion_name" data-dispname=" マンション（名称 : " type="text" value="" style="ime-mode:active;" class="text chk_input text50" placeholder="" />
                                                    </label></li>

                                                <li>
                                                    <input type="radio" name="kibo_type" siqatrib="kibo_type" data-dispname="査定希望物件の種別" id="radio1_4" data-group="hisu1" class="chk_input chk_required" value="その他" />
                                                    <label for="radio1_4" class="radio">その他

                                                        <input name="kibo_type_other" data-dispname="その他 " type="text" value="" style="ime-mode:active;" class="text chk_input text50" placeholder="" />
                                                    </label></li>
                                            </ul>
                                        </td>
                                    </tr>


                                    <tr>
                                        <th>築年</th>
                                        <td colspan="2">
                                            <input type="radio" name="chikunengo" siqatrib="chikunengo" data-dispname="築年(年号)" id="radio2_1" data-group="hisu2" class="chk_input " value="昭和" />
                                            <label for="radio2_1" class="radio">昭和</label>

                                            <input type="radio" name="chikunengo" siqatrib="chikunengo" data-dispname="築年(年号)" id="radio2_2" data-group="hisu2" class="chk_input" value="平成" />
                                            <label for="radio2_2" class="radio">平成</label>

                                            <!--最大3桁／半角数字入力-->
                                            <input name="chikunen" siqatrib="chikunen" data-dispname=" 年築" type="tel" value="" class="text chk_input chk_num text10" maxlength="3" placeholder="半角数字" style="ime-mode:disabled;" /> 年築
                                        </td>
                                    </tr>


                                    <tr>
                                        <th>間取り</th>
                                        <td colspan="2">（左欄に数字を入力、右欄でタイプを選択）<br />
                                            <!--最大2桁／半角数字入力-->
                                            <input name="madori" siqatrib="madori" type="tel" class="text chk_input chk_num text10" maxlength="2" placeholder="半角数字" style="ime-mode:disabled;" />

                                            <select name="madori2" siqatrib="madori2" data-dispname="件名" id="件名" class="chk_input">
                                                <option selected="selected">選択して下さい</option>
                                                <option value="L">L</option>
                                                <option value="DK">DK</option>
                                                <option value="LK">LK</option>
                                                <option value="LDK">LDK</option>
                                                <option value="SK">SK</option>
                                                <option value="SDK">SDK</option>
                                                <option value="SLK">SLK</option>
                                                <option value="SLDK">SLDK</option>
                                                <option value="ワンルーム">ワンルーム</option>
                                            </select>
                                        </td>
                                    </tr>



                                    <tr>
                                        <th>土地・建物面積</th>
                                        <td colspan="2">▼一戸建、土地を選択された方は入力して下さい。<br />

                                            <ul class="tate">
                                                <li>
                                                    土地面積
                                                    <!--最大3桁／半角数字入力-->
                                                    <input name="land_area" siqatrib="land_area" type="tel" id="land_area" class="text chk_input chk_num text20" maxlength="3" placeholder="半角数字" style="ime-mode:disabled;" />

                                                    <input type="radio" name="land_area_unit" siqatrib="land_area_unit" data-dispname="土地面積単位" id="radio3_1" data-group="hisu3" class="chk_input" value="m2" />
                                                    <label for="radio3_1" class="radio">㎡</label>

                                                    <input type="radio" name="land_area_unit" siqatrib="land_area_unit" data-dispname="土地面積単位" id="radio4_2" data-group="hisu3" class="chk_input" value="坪" />
                                                    <label for="radio4_2" class="radio">坪</label>
                                                </li>

                                                <li>
                                                    建物面積
                                                    <!--最大3桁／半角数字入力-->
                                                    <input name="bld_area" siqatrib="bld_area" type="tel" id="bld_area" class="text chk_input chk_num text20" maxlength="3" placeholder="半角数字" style="ime-mode:disabled;" />

                                                    <input type="radio" name="bld_area_unit" siqatrib="bld_area_unit" data-dispname="建物面積単位" id="radio5_1" data-group="hisu3" class="chk_input" value="m2" />
                                                    <label for="radio5_1" class="radio">㎡</label>

                                                    <input type="radio" name="bld_area_unit" siqatrib="bld_area_unit" data-dispname="建物面積単位" id="radio5_2" data-group="hisu3" class="chk_input" value="坪" />
                                                    <label for="radio5_2" class="radio">坪</label>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>



                                    <tr>
                                        <th>専有面積など</th>
                                        <td colspan="2">▼マンションを選択された方は入力して下さい。<br />

                                            <input type="radio" name="senyu_area_unit" siqatrib="senyu_area_unit" data-dispname="専有面積単位" id="radio6_1" data-group="hisu4" class="text chk_input" value="専有面積(m2)" />専有面積
                                            <label for="radio6_1" class="radio">
                                                <!--最大3桁／半角数字入力--><input name="senyu_area1" siqatrib="senyu_area1" type="tel"  class="text chk_input chk_num text10" maxlength="3" placeholder="半角数字" style="ime-mode:disabled;" />  ㎡
                                            </label>

                                            <input type="radio" name="senyu_area_unit" siqatrib="senyu_area_unit" data-dispname="専有面積単位" id="radio6_2" data-group="hisu4" class="chk_input" value="坪" />
                                            <label for="radio6_2" class="radio">
                                                <!--最大3桁／半角数字入力--><input name="senyu_area2" siqatrib="senyu_area2" type="tel"  class="text chk_input chk_num text10" maxlength="3" placeholder="半角数字" style="ime-mode:disabled;" />
                                                坪（ 
                                                <!--最大3桁／半角数字入力--><input name="senyu_kaisu" siqatrib="senyu_kaisu" type="tel"  class="text chk_input chk_num text10" maxlength="2" placeholder="半角数字" style="ime-mode:disabled;" /> 階部分）
                                            </label>
                                        </td>
                                    </tr>


                                    <tr>
                                        <th><div class="anq_required">物件所在地<span class="must">必須</span></div></th>
                                        <td colspan="2"><input name="shozaichi" siqatrib="shozaichi" id="shozaichiID" data-dispname="物件所在地" type="text" value="" style="ime-mode:active;" class="text chk_input chk_required text60"placeholder="神奈川県平塚市東八幡3-16-16" /></td>
                                    </tr>

                                    <tr>
                                        <th>ご希望売却価格</th>
                                        <td colspan="2">
                                            <!--最大10桁／半角数字入力--><input name="kibo_price" id="kibo_priceID" type="tel" value="" siqatrib="kibo_price" class="chk_input chk_num text10" maxlength="7" placeholder="半角数字" class="text" style="ime-mode:disabled;" />
                                            万円くらい</td>
                                    </tr>

                                    <tr>
                                        <!--<th>ご売却又は買替え動機</th>-->
                                        <th>ご売却について</th>
                                        <td><textarea name="douki" siqatrib="douki" id="doukiID" data-dispname="ご売却について" rows="6" style="ime-mode:active;" class="chk_input" placeholder="内容をご入力してください。"></textarea></td>
                                    </tr>

                                    <tr>
                                        <th>売却予定時期</th>
                                        <td colspan="2">
                                            <input name="kibo_time" siqatrib="kibo_time" data-dispname="売却予定時期" data-group="hisu6" id="checkbox11" class="chk_input" type="checkbox" value="早急" />
                                            <label for="checkbox11" class="checkbox">早急</label>

                                            <input name="kibo_time" siqatrib="kibo_time" data-dispname="売却予定時期" data-group="hisu6" id="checkbox12" class="chk_input" type="checkbox" value="3ヶ月以内 " />
                                            <label for="checkbox12" class="checkbox">3ヶ月以内 </label>

                                            <input name="kibo_time" siqatrib="kibo_time" data-dispname="売却予定時期" data-group="hisu6" id="checkbox13" class="chk_input" type="checkbox" value="半年〜1年以内" />
                                            <label for="checkbox13" class="checkbox">半年〜1年以内 </label>

                                            <input name="kibo_time" siqatrib="kibo_time" data-dispname="売却予定時期" data-group="hisu6" id="checkbox14" class="chk_input" type="checkbox" value="未定" />
                                            <label for="checkbox14" class="checkbox">未定</label>
                                        </td>
                                    </tr>

                                    <tr>
                                        <th>正確な査定を希望する</th>
                                        <td colspan="2">
                                            <input type="radio" name="correct_kibo" siqatrib="correct_kibo" data-dispname="正確な査定を希望" id="radio7_1" data-group="hisu7" class="chk_input" value="はい" />
                                            <label for="radio7_1" class="radio">はい</label>

                                            <input type="radio" name="correct_kibo" siqatrib="correct_kibo" data-dispname="正確な査定を希望" id="radio7_2" data-group="hisu7" class="chk_input" value="いいえ" />
                                            <label for="radio7_2" class="radio">いいえ</label>
                                        </td>
                                    </tr>
                                </table>

                                <!------------------------------------------------------------------------
                                -------------------------------------------------------------------------->

                                <h2>お客様情報</h2>
                                <?php include(__DIR__.'/form_parts/kokyaku_input.inc'); ?>

                                <div id="privacy">
                                    <p class="open">弊社の<span>プライバシーポリシー</span>をお読みいただき、すべての内容に同意のうえご登録ください。</p>
                                    <?php include(__DIR__.'/form_parts/privacy_policy.inc'); ?>
                                    <!--/privacy-->
                                </div>
                                <div id="submit">
                                    <input type="submit" value="上記の内容で送信する" class="css_btn_class maru" onclick="myFunction();" />
                                    <!--/submit-->
                                </div>
                            </form>
                        </div>
                        <!--formWrap-->
                    </div>


                    <!--/inner-->
                </div>
                <!--/assessment-->
            </div>
            <!--/contents-->
        </div>

        <?php include(__DIR__.'/../web/inc/footerbanner.inc'); ?>
        <?php include(__DIR__.'/../web/inc/footer.inc'); ?>
    </div>
    <p class="pagetop"><a href="#container">▲</a></p>
    
    <?php include(__DIR__.'/../web/inc/sidebt.inc'); ?>
    <?php include(__DIR__.'/../web/inc/footbt.inc'); ?>
</body>
</html>
