<!DOCTYPE HTML>
<html>
<head>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NKFL2BN');</script>
<!-- End Google Tag Manager -->
<meta charset="UTF-8">
<meta name="robots" content="noindex">
<meta name="viewport" content="width=device-width" />
<title>来店予約フォーム｜センチュリー21住宅セレクション: 神奈川エリアの不動産売買専門</title>
<meta name="Description" content="センチュリー21住宅セレクションの来店予約フォーム" />
<meta name="Keywords" content="おすすめ物件,センチュリー21住宅セレクション,神奈川県藤沢市,茅ヶ崎市,平塚市,寒川町,不動産,売買専門" />
<link rel="stylesheet" href="/css/style.css" />
<link rel="stylesheet" href="/css/form.css" />
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
<!--&#91;if lt IE 9&#93;>
<script src="//cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
<!&#91;endif&#93;-->
<script src="https://code.jquery.com/jquery-latest.js"></script>
<script src="/js/common.js"></script>
<script type="text/javascript" src="//webfont.fontplus.jp/accessor/script/fontplus.js?KxqpanDaumc%3D&box=~8PqL6Bf2q8%3D&aa=1" charset="utf-8"></script>
<!---------------------
　スマホナビゲーション
----------------------->
<script type="text/javascript" src="/js/jquery.meanmenu.js"></script>
<link href="/css/meanmenu.css" rel="stylesheet" type="text/css">
<script>
(function($){
	$(function(){	
		$('#spheader').meanmenu({
			meanMenuClose: "x",
			meanMenuCloseSize: "18px",
			meanMenuOpen: "<span /><span /><span />",
			meanRevealPosition: "right",
			meanRevealColour: "",
			meanScreenWidth: "480"
		});
	});	
})(jQuery);
</script>
<!---------------------
　フォーム関連
----------------------->
<link rel="stylesheet" href="/css/inputchk.css" type="text/css" />
<script type="text/javascript" src="/js/inputchk.js"></script>
<!--送信チェック-->
<script type="text/javascript">
function sendMail() {
	var ret = checkSubmit();
	if (ret) {
		if(confirm("送信してもよろしいですか？")){
			return true;
		} else {
			return false;
		}
	}
	return ret;
}
</script>
<!--離脱アラート-->
<script>
jQuery(
 function($)
 {
	var loc=false;
     //store onbeforeunload for later use
   $(window).bind("beforeunload", function(e) {
 // 確認メッセージに表示させたい文字列を返します。
 if (!loc) {
 return "お問合せは完了しておりません。このページから移動してもよろしいですか？";
 }
});
//$('a').click( function() {loc=true;});
$("form").submit(function(){loc=true;});
 }
);
</script>
<!-------------------------------
toggle 表示・非表示
--------------------------------->
<script type="text/javascript">
	$(function(){
		
		//最初から非表示
		$('.pvbox').hide();
		$(".open").click(function(){
			$(this).next().slideToggle();
		});
	});
</script>
<script type="text/javascript" src="//ajaxzip3.github.io/ajaxzip3.js" charset="utf-8"></script>

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5GPT3H');</script>
<!-- End Google Tag Manager -->
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '2805189076247155');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=2805189076247155&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->


<script type="text/javascript">
    function myFunction() {
        var post_data = {};
        
        var name = $("#kokyaku_nameID").val();
        var email = $("#mail_addr1ID").val();
        
        $zoho.salesiq.visitor.name(name);
        $zoho.salesiq.visitor.email(email);
    }
</script>

<script type="text/javascript" src="/js_arcs/line_parameter.js"></script>

</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NKFL2BN"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div id="container">
<?php include(__DIR__.'/../web/inc/header.inc'); ?>
<?php include(__DIR__.'/../web/inc/nav.inc'); ?>
<div id="contents">
<div id="sptop" class="pchd">
<a href="/loan_consultation/"><img src="/image/sptop.png" alt="住宅ローン審査の通過実績多数!! "></a>
</div>
<div id="form">
<div class="inner">
<ol class="topicPath sphd">
<li><a href="/">センチュリー21 住宅セレクション</a></li>
<li>来店予約フォーム</li>
</ol>
<h1><i class="fas fa-edit"></i>　来店予約フォーム</h1>
<p class="mgb10">来店のご予約は、下記フォームをご利用ください。後程、担当者より御連絡させて頂きます。<br>
お客様以外の利用はご遠慮願います。こちらのフォームはお客様専用フォームとなります。</p>
<div class="yoyakutop">
<img class="mgb20" src="/image/raiten.jpg" alt="QUOカードプレゼントキャンペーン">
<p class="att mgb20">
・QUOカードのプレゼントは、１名様（１家族様）１回限りとさせて頂きます。<br>
・未成年者様のみのご来店は対象外とさせて頂きます。<br>
・アンケートにご協力して頂く事が条件となります。
</p>
<p class="raiten">来店予約からプレゼントまでの流れ</p>
<img src="/image/raiten_step.jpg" alt=""></div>

<form id="mailform" method="post" action="/bin/common-contact.php">
<input type="hidden" id="type" name="type" value="raiten" />
<input type="hidden" id="mode" name="mode" value="confirm" />
<?php echo $hidden_html; ?>

<div id="formWrap">
<h2>来店・案内のご希望について</h2>
<table class="pc_raiten">
<tr class="raiten_yoyaku_form_title">
<th>ご来店希望日時<span class="must">必須</span></th>
<td>
第一希望　
■ 日程 : <select name="toiawase_naiyou1_date" data-dispname="ご希望日" siqatrib="toiawase_naiyou1_date" id="toiawase_naiyou1_dateID" class="chk_input chk_required">
<option value="">指定なし</option>
<?php
	foreach ($form_cds['yoyaku_date'] as &$value) {
		$selected = ($value[cd] == $Param['toiawase_naiyou1_date']) ? " selected" : "";
		echo '<option value="'.$value[cd].'"'.$selected.'>'.$value[nm].'</option>';
	}
?>
</select>　
■ 時間 : <select name="toiawase_naiyou1_time" data-dispname="ご希望日時間" siqatrib="toiawase_naiyou1_time" id="toiawase_naiyou1_timeID" class="chk_input chk_required">
<option value="指定なし">指定なし　　　　</option>
<?php
	foreach ($form_cds['yoyaku_jikan'] as &$value) {
		$selected = ($value[cd] == $Param['toiawase_naiyou1_time']) ? " selected" : "";
		echo '<option value="'.$value[cd].'"'.$selected.'>'.$value[nm].'</option>';
	}
?>
</select><br>
第二希望　
■ 日程 : <select name="toiawase_naiyou2_date" data-dispname="ご希望日" id="ご希望日" class="chk_input chk_required">
<option value="">指定なし</option>
<?php
	foreach ($form_cds['yoyaku_date'] as &$value) {
		$selected = ($value[cd] == $Param['toiawase_naiyou2_date']) ? " selected" : "";
		echo '<option value="'.$value[cd].'"'.$selected.'>'.$value[nm].'</option>';
	}
?>
</select>　
■ 時間 : <select name="toiawase_naiyou2_time" data-dispname="ご希望日時間" id="ご希望日時間" class="chk_input chk_required">
<option value="指定なし">指定なし　　　　</option>
<?php
	foreach ($form_cds['yoyaku_jikan'] as &$value) {
		$selected = ($value[cd] == $Param['toiawase_naiyou2_time']) ? " selected" : "";
		echo '<option value="'.$value[cd].'"'.$selected.'>'.$value[nm].'</option>';
	}
?>
</select></td>
</tr>
<tr>
<th>ご来店される店舗<span class="must">必須</span></th>
<td>
<ul>
<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_1" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="平塚店" checked="checked" />
<label for="radio1_1" class="radio">平塚店</label>（<a href="https://goo.gl/maps/TVdM7ui7xP22" target="_blank">Map</a>）</li>
<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_5" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="小田原店" />
<label for="radio1_5" class="radio">小田原店</label>（<a href="https://goo.gl/maps/8SWCCeJenjnCeNgRA" target="_blank">Map</a>）</li>

<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_11" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="海老名住宅ローン相談会場" />
<label for="radio1_11" class="radio">海老名住宅ローン相談会場</label>（<a href="https://goo.gl/maps/Bsu5BgmjHSCPc6g47" target="_blank">Map</a>）</li>
<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_21" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="茅ヶ崎住宅ローン相談会場" />
<label for="radio1_21" class="radio">茅ヶ崎住宅ローン相談会場</label>（<a href="https://maps.app.goo.gl/rym16eXEaVoJk8TT8" target="_blank">Map</a>）</li>
<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_12" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="藤沢住宅ローン相談会場" />
<label for="radio1_12" class="radio">藤沢住宅ローン相談会場</label>（<a href="https://goo.gl/maps/bssii1DD6tPpP6Sg9" target="_blank">Map</a>）</li>

<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_22" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="本厚木住宅ローン相談会場" />
<label for="radio1_22" class="radio">本厚木住宅ローン相談会場</label>（<a href="https://maps.app.goo.gl/cUKtZFcRquwymz669" target="_blank">Map</a>）</li>
<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_9" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="横浜（関内）住宅ローン相談会場" />
<label for="radio1_9" class="radio">横浜（関内）住宅ローン相談会場</label>（<a href="https://goo.gl/maps/QsYgkiQ52ApQq8WC8" target="_blank">Map</a>）</li>
<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_10" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="横浜（桜木町）住宅ローン相談会場" />
<label for="radio1_10" class="radio">横浜（桜木町）住宅ローン相談会場</label>（<a href="https://goo.gl/maps/8xFzRCq6V56fZM7w6" target="_blank">Map</a>）</li>

<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_23" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="川崎駅東口住宅ローン相談会場" />
<label for="radio1_23" class="radio">川崎駅東口住宅ローン相談会場</label>（<a href="https://maps.app.goo.gl/aPrbWCEnm82Weypz6" target="_blank">Map</a>）</li>
<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_4" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="相模原住宅ローン相談会場" />
<label for="radio1_4" class="radio">相模原住宅ローン相談会場</label>（<a href="https://goo.gl/maps/rrTZLvWLGAk" target="_blank">Map</a>）</li>
<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_13" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="平塚駅前住宅ローン相談会場" />
<label for="radio1_13" class="radio">平塚駅前住宅ローン相談会場</label>（<a href="https://goo.gl/maps/FAWYcys5uC3yZkbBA" target="_blank">Map</a>）</li>

<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_24" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="小田原駅前住宅ローン相談会場" />
<label for="radio1_24" class="radio">小田原駅前住宅ローン相談会場</label>（<a href="https://maps.app.goo.gl/ghHqmo36UeSawzCs8" target="_blank">Map</a>）</li>
<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_14" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="町田住宅ローン相談会場" />
<label for="radio1_14" class="radio">町田住宅ローン相談会場</label>（<a href="https://goo.gl/maps/Cn2y16ZEbQy5PNpE9" target="_blank">Map</a>）</li>
<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_15" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="橋本住宅ローン相談会場" />
<label for="radio1_15" class="radio">橋本住宅ローン相談会場</label>（<a href="https://goo.gl/maps/gYdBf71zefrVckQb7" target="_blank">Map</a>）</li>

<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_16" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="センター北住宅ローン相談会場" />
<label for="radio1_16" class="radio">センター北住宅ローン相談会場</label>（<a href="https://goo.gl/maps/1GwVtBHoPy4ARAs16" target="_blank">Map</a>）</li>
<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_17" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="新横浜住宅ローン相談会場" />
<label for="radio1_17" class="radio">新横浜住宅ローン相談会場</label>（<a href="https://goo.gl/maps/CDtUuaWhukNGATiP6" target="_blank">Map</a>）</li>
<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_18" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="溝の口住宅ローン相談会場" />
<label for="radio1_18" class="radio">溝の口住宅ローン相談会場</label>（<a href="https://goo.gl/maps/xyyrrxzL4uNvwvwUA" target="_blank">Map</a>）</li>

<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_19" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="品川住宅ローン相談会場" />
<label for="radio1_19" class="radio">品川住宅ローン相談会場</label>（<a href="https://goo.gl/maps/fLvxzb45V6bVmJkV9" target="_blank">Map</a>）</li>
<li><input type="radio" name="toiawase_naiyou3" data-dispname="ご来店される店舗" id="radio1_20" siqatrib="toiawase_naiyou3" data-group="hisu1" class="chk_input chk_required" value="蒲田住宅ローン相談会場" />
<label for="radio1_20" class="radio">蒲田住宅ローン相談会場</label>（<a href="https://goo.gl/maps/ZTZJBMHZaJarSMsb7" target="_blank">Map</a>）</li>
</td>
</tr>
<tr class="raiten_yoyaku_form_title">
<th>その他ご連絡事項など</th>
<td><textarea name="free_text" id="free_textID" siqatrib="free_text" style="ime-mode:active;width: 99%" class="その他ご連絡事項" siqatrib="free_text" cols="50" rows="5"></textarea></td>
</tr>
<tr class="raiten_yoyaku_form_content">
</tr>
</table>
<h2>お客様情報</h2>
<?php include(__DIR__.'/form_parts/kokyaku_input.inc'); ?>

<div id="privacy">
<p class="open">弊社の<span>プライバシーポリシー</span>をお読みいただき、すべての内容に同意のうえご登録ください。</p>
<?php include(__DIR__.'/form_parts/privacy_policy.inc'); ?>
<!--/privacy-->
</div>
<div id="submit">
<input type="submit" value="上記の内容で確認する" onclick="myFunction()" class="css_btn_class maru" />
<!--/submit-->
</div>
<!--/formWrap-->
</div>

<input type='text' style='display:none;' name='xnQsjsdp' value='d350a3237154fdd102f61a9e00bf1a531735217e474ba6be69ee793314e7c15a'/>
<input type='hidden' name='zc_gad' id='zc_gad' value=''/>
<input type='text' style='display:none;' name='xmIwtLD' value='a874bac5e1893146a6b58ad8ce95645d47981355839b1a0dac348a4fa6f013b7'/>
<input type='text'  style='display:none;' name='actionType' value='TGVhZHM='/>
<input type='text' style='display:none;' name='returnURL' value='https&#x3a;&#x2f;&#x2f;crmplus.zoho.com&#x2f;housedemoaccount&#x2f;index.do&#x2f;cxapp&#x2f;crm&#x2f;org769615357&#x2f;tab&#x2f;Leads&#x2f;custom-view&#x2f;5162417000000087501&#x2f;canvas&#x2f;5162417000000353007' />
<script id='wf_anal' src='https://crm.zohopublic.com/crm/WebFormAnalyticsServeServlet?rid=a874bac5e1893146a6b58ad8ce95645d47981355839b1a0dac348a4fa6f013b7gidd350a3237154fdd102f61a9e00bf1a531735217e474ba6be69ee793314e7c15agid885e3c1045bd9bdcc91bdf30f82b5696gid14f4ec16431e0686150daa43f3210513'></script>
</form>
<div class="note">
<dl>
<dt>新型コロナウイルス感染防止対策について</dt>
<dd>弊社では新型コロナ対策として接客時の従業員のマスク着用、接客前後の手洗い及び消毒、接客後のテーブル、椅子の除菌清掃、お客様との間を隔てるアクリル板の設置、および
定期的な換気を徹底した上、ご対応をさせて頂いておりますので、ご安心してご来店ください。<br>
大変ご不便、ご迷惑をおかけいたしますが、何卒ご理解いただきますようお願い申し上げます。</dd>
</dl>
<!--/note-->
</div>
<!--/inner-->
</div>
<!--/form-->
</div>
<!--/contents-->
</div>
<?php include(__DIR__.'/../web/inc/footer.inc'); ?>
<!--/container-->
</div>
<p class="pagetop"><a href="#container">▲</a></p>
<?php include(__DIR__.'/../web/inc/sidebt.inc'); ?>
<?php include(__DIR__.'/../web/inc/footbt.inc'); ?>
</body>
</html>
