<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" lang="ja">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>トピックス一覧｜葛飾区 新築一戸建て 土地はガクエン住宅水元本社へ</title>
<meta name="description" content="ガクエン住宅からの最新トピックス一覧ページ。葛飾区の新築一戸建て・土地等の優良不動産物件を写真・間取付でご紹介。お問い合わせは0120-276-313までお気軽に！" />
<meta name="keywords" content="不動産,葛飾区,足立区,一戸建て,土地,トピックス" />
<meta name="viewport" content="width=device-width" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<link rel="index" href="https://www.gakuen-j.co.jp/" />
<link rev="made" href="info@gakuen-j.co.jp" />
<link rel="canonical" href="https://www.gakuen-j.co.jp/" />
<!--ディスプレイサイズ 横幅1025px以上（PC）用＆印刷用-->
<link rel="stylesheet" media="print, screen and (min-width: 641px)" href="/css/common.css">
<link rel="stylesheet" media="print, screen and (min-width: 641px)" href="/css/base.css">
<link rel="stylesheet" media="print, screen and (min-width: 641px)" href="/css/navi.css">
<link rel="stylesheet" media="print, screen and (min-width: 641px)" href="/css/button.css">
<link rel="stylesheet" media="print, screen and (min-width: 641px)" href="/css/topics.css">
<!--ディスプレイサイズ 横幅640px以下（iphone）用-->
<link rel="stylesheet" media="screen and (max-width: 640px)" href="/css/common_sp.css">
<link rel="stylesheet" media="screen and (max-width: 640px)" href="/css/base_sp.css">
<link rel="stylesheet" media="screen and (max-width: 640px)" href="/css/button_sp.css">
<link rel="stylesheet" media="screen and (max-width: 640px)" href="/css/topics_sp.css">
<script src="https://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript" src="/js/common.js"></script>
<script type="text/javascript" src="/js/rollover.js"></script>
<!--▼/head内　page only ------------------------------------------------------------------->
<link rel="stylesheet" href="/css/pager.css"> 
<script type="text/javascript" src="/js_arcs/topicslist.js"></script>
<!-------------------------------
ポップアップ
--------------------------------->
<link rel="stylesheet" href="/css/magnific-popup.css"> 
<script src="/js/magnific-popup/jquery.magnific-popup.js"></script>
<script src="/js/magnific-popup/jquery.magnific-popup_OP.js"></script>
<!--▲/head内　page only ----------------------------------------------------------------->
<!-------------------------------
ファビコン・タッチアイコン
--------------------------------->
<meta name="apple-mobile-web-app-title" content="ガクエン住宅">
<!-- iOS Safari and Chrome -->
<link rel="apple-touch-icon" sizes="192x192" href="https://www.gakuen-j.co.jp/touch-icon.png">
<!-- Android標準ブラウザ(一部) -->
<link rel="shortcut icon" href="https://www.gakuen-j.co.jp/touch-icon.png">
<!--ファビコン-->
<link rel="shortcut icon" href="https://www.gakuen-j.co.jp/favicon.ico" />
<!--------------------------------
▼font
---------------------------------->
<script type="text/javascript" src="//typesquare.com/accessor/script/typesquare.js?H1xrEdKIES8%3D" charset="utf-8"></script>
<!-------------------------------
▼menu
--------------------------------->
<script type="text/javascript" src="/js/jquery.leanModal.min.js"></script>
<script>
$(function(){
      $("#menu").click(function(){
      	$("ul.dropmenu").slideToggle('fast');
      });
});
$(function() {/*複数設置*/
    $( 'a[rel*=leanModal]').leanModal({
        top: 50,
        overlay : 0.8,
    });
}); 
</script>
<!-------------------------------
▼pagetop
--------------------------------->
<script type="text/javascript" src="/js/pagetop.js"></script>
<!--------------------------------
▼旧ブラウザ　html5対応
---------------------------------->
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!--------------------------------
▼Analytics
---------------------------------->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-13100855-1']);
  _gaq.push(['_setDomainName', 'gakuen-j.co.jp']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<!--------------------------------
▼Marketing Analitics & Chat  START 150403
---------------------------------->
<script  type="text/javascript">
//<![CDATA[
function logCorpAScript_full(){
	HTTP_MSN_MEMBER_NAME="";/*member name*/
	var prtc=(document.location.protocol=="https:")?"https://":"http://";
	var hst=prtc+"suite.log-marketing.jp";
	var rnd="r"+(new  Date().getTime()*Math.random()*9);
	this.ch=function(){
		if(document.getElementsByTagName("head")[0]){this.dls();}else{window.setTimeout(logCorpAnalysis_full.ch,30)}
	}
	this.dls=function(){
		var  h=document.getElementsByTagName("head")[0];
		var  s=document.createElement("script");s.type="text/jav"+"ascript";try{s.defer=true;}catch(e){};try{s.async=true;}catch(e){};
		if(h){s.src=hst+"/HTTP_MSN/UsrConfig/sem_athome/js/ASP_Conf.js?s="+rnd;h.appendChild(s);}
	}
	this.init= function(){
		document.write('<img src="'+hst+'/sr.gif?d='+rnd+'"  style="width:1px;height:1px;position:absolute;" alt="" onload="logCorpAnalysis_full.ch()" />');
	}
}
if(typeof logCorpAnalysis_full=="undefined"){	var logCorpAnalysis_full=new logCorpAScript_full();logCorpAnalysis_full.init();}
//]]>
</script>
<noscript>
<img src="http://suite.log-marketing.jp/HTTP_MSN/Messenger/Noscript.php?key=sem_athome" border="0" style="display:none;width:0;height:0;" />
</noscript>

<script type="text/javascript">
$(function(){
	$('.pgj').click(function(){
		$('#page_num').val($(this).attr('vval'));
		$('#searchf').submit();
	});
});
</script>

</head>



<body>
<div id="container"> 

<div id="header_PC">
<?php include('inc/header.inc'); ?>
<!--header_PC-->
</div>
<?php include('inc/header_sp.inc'); ?>



<div class="breadcrumb-list">
<ul>
<li><a href="/">ガクエン住宅トップ</a> &gt;</li>
<li>トピックス一覧</li>
</ul>
</div>

<div id="contents"> 
<div class="box">
<div class="tit">トピックス一覧</div>



<form id="searchf" action="/bin/topics-list.php" method="post">
<input type="hidden" id="page_num" name="page_num" value="<?php echo $Param['page_num']; ?>" />
</form>

<div class="topics">
<!---------------------------
▼ページャー 1ページに20件表示
----------------------------->
<div class="paginate">
<ul>
<?php if ($page_prev != ""){ ?>
<li class="prev"><a href="javascript:void(0)" class="pgj" vval="<?php echo $page_prev; ?>">前へ</a></li>
<?php } ?>
<?php
	for ($i = 1; $i <= $all_page_num; $i++) {
		if($i==$Param['page_num']){
			echo '<li><a class="on">'.$i.'</a></li>';
		}else{
			echo '<li><a href="javascript:void(0)" class="pgj" vval="'.$i.'">'.$i.'</a></li>';
		}
	}
?>

<?php if ($page_next != ""){ ?>
<li class="next"><a href="javascript:void(0)" class="pgj" vval="<?php echo $page_next; ?>">次へ</a></li>
<?php } ?>
</ul>
</div>

<!---------------------------
▲ページャー
----------------------------->
<div class="inner">
<ul class="topics_box">
<!---------------------------
▼1ページに20件表示
----------------------------->
<?php
	foreach ($TopicsList as &$value) {
		$obj_link = "<a class=\"hv\" href=\"/bin/topics-detail.php?topics_cd=".$value['topics_cd']."\" target=\"_blank\">";
		if ($value['topics_url'] != ""){
			$obj_link = "<a class=\"hv\" href=\"".$value['topics_url']."\" target=\"_blank\">";
		}
?>



<li class="border"><?php echo $obj_link; ?>
<dl>
<dt>
<p class="date"><?php echo $value['topics_date_ymd']; ?></p>
<p class="title"><?php echo nl2br($value['topics_title']); ?></p>
</dt>
<dd>
<p class="text"><?php echo nl2br($value['topics_detail']); ?></p>
</dd>
</dl>
</a></li>
<?php
	}
?>
<!---------------------------

▲1ページに20件表示

----------------------------->
</ul>
<!--/inner--> 
</div>
<!---------------------------
▼ページャー 
----------------------------->
<div class="paginate">
<ul>
<?php if ($page_prev != ""){ ?>
<li class="prev"><a href="javascript:void(0)" class="pgj" vval="<?php echo $page_prev; ?>">前へ</a></li>
<?php } ?>
<?php
	for ($i = 1; $i <= $all_page_num; $i++) {
		if($i==$Param['page_num']){
			echo '<li><a class="on">'.$i.'</a></li>';
		}else{
			echo '<li><a href="javascript:void(0)" class="pgj" vval="'.$i.'">'.$i.'</a></li>';
		}
	}
?>

<?php if ($page_next != ""){ ?>
<li class="next"><a href="javascript:void(0)" class="pgj" vval="<?php echo $page_next; ?>">次へ</a></li>
<?php } ?>
</ul>
</div>
<!---------------------------
▲ページャー
----------------------------->
<!--/topics--> 
</div>


<!--box-->
</div>


<!--/contents--> 
</div>



<?php include('inc/footer.html'); ?>
<!--/container-->
</div>





<!--▼/body前------------------------------------------------------------------->
<?php include('inc/tag_body.html'); ?>
<!--▲/body前------------------------------------------------------------------->
</body>
</html>

