<!DOCTYPE HTML>
<html>
<head>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NKFL2BN');</script>
<!-- End Google Tag Manager -->
<meta charset="UTF-8">
<meta name="robots" content="noindex">
<meta name="viewport" content="width=device-width" />
<title>来場予約フォーム｜センチュリー21住宅セレクション: 神奈川エリアの不動産売買専門</title>
<meta name="Description" content="センチュリー21住宅セレクションの来場予約フォーム" />
<meta name="Keywords" content="おすすめ物件,センチュリー21住宅セレクション,神奈川県藤沢市,茅ヶ崎市,平塚市,寒川町,不動産,売買専門" />

<?php // canonical タグの表示
    echo '<link rel="canonical" href="http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'].'">';
?>

<link rel="stylesheet" href="/css/style.css" />
<link rel="stylesheet" href="/css/form.css" />
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
<!--&#91;if lt IE 9&#93;>
<script src="//cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
<!&#91;endif&#93;-->
<script src="https://code.jquery.com/jquery-latest.js"></script>
<script src="/js/common.js"></script>
<script type="text/javascript" src="//webfont.fontplus.jp/accessor/script/fontplus.js?KxqpanDaumc%3D&box=~8PqL6Bf2q8%3D&aa=1" charset="utf-8"></script>
<!---------------------
　スマホナビゲーション
----------------------->
<script type="text/javascript" src="/js/jquery.meanmenu.js"></script>
<link href="/css/meanmenu.css" rel="stylesheet" type="text/css">
<script>
(function($){
	$(function(){	
		$('#spheader').meanmenu({
			meanMenuClose: "x",
			meanMenuCloseSize: "18px",
			meanMenuOpen: "<span /><span /><span />",
			meanRevealPosition: "right",
			meanRevealColour: "",
			meanScreenWidth: "480"
		});
	});	
})(jQuery);
</script>
<!---------------------
　フォーム関連
----------------------->
<link rel="stylesheet" href="/css/inputchk.css" type="text/css" />
<script type="text/javascript" src="/js/inputchk.js"></script>
<!--送信チェック-->
<script type="text/javascript">
function sendMail() {
	var ret = checkSubmit();
	if (ret) {
		if(confirm("送信してもよろしいですか？")){
			return true;
		} else {
			return false;
		}
	}
	return ret;
}
</script>
<!--離脱アラート-->
<script>
jQuery(
 function($)
 {
	var loc=false;
     //store onbeforeunload for later use
   $(window).bind("beforeunload", function(e) {
 // 確認メッセージに表示させたい文字列を返します。
 if (!loc) {
 return "お問合せは完了しておりません。このページから移動してもよろしいですか？";
 }
});
//$('a').click( function() {loc=true;});
$("form").submit(function(){loc=true;});
 }
);
</script>
<!-------------------------------
toggle 表示・非表示
--------------------------------->
<script type="text/javascript">
	$(function(){
		
		//最初から非表示
		$('.pvbox').hide();
		$(".open").click(function(){
			$(this).next().slideToggle();
		});
	});
</script>
<script type="text/javascript" src="//ajaxzip3.github.io/ajaxzip3.js" charset="utf-8"></script>

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5GPT3H');</script>
<!-- End Google Tag Manager -->
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '2805189076247155');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=2805189076247155&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->


<script type="text/javascript">
    function myFunction() {
        var post_data = {};
        
        var name = $("#kokyaku_nameID").val();
        var email = $("#mail_addr1ID").val();
        
        $zoho.salesiq.visitor.name(name);
        $zoho.salesiq.visitor.email(email);
    }
</script>



</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NKFL2BN"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div id="container"> 
<?php include(__DIR__.'/../web/inc/header.inc'); ?>
<?php include(__DIR__.'/../web/inc/nav.inc'); ?>
<div id="sptop" class="pchd"> <a href="/loan_consultation/"><img src="/image/sptop.png" alt="住宅ローン審査の通過実績多数!! "></a>
</div>
<div id="contents">
<div id="form">
<div class="inner">
<ol class="topicPath sphd">
<li><a href="/">センチュリー21 住宅セレクション</a></li>
<li>来場予約フォーム</li>
</ol>
<h1><i class="fas fa-edit"></i>　来場予約フォーム</h1>
<p class="mgb20">見学のご予約は、下記フォームをご利用ください。後程、担当者より御連絡させて頂きます。<br>
お客様以外の利用はご遠慮願います。こちらのフォームはお客様専用フォームとなります。</p>

<form id="mailform" method="post" action="/bin/common-contact.php">
    <input type="hidden" id="type" name="type" value="yoyaku" />
    <input type="hidden" id="mode" name="mode" value="confirm" />
    <?php echo $hidden_html; ?>
    
    
    <div id="formtop2">
        <h2>お問い合わせ物件</h2>
        <?php include(__DIR__.'/form_parts/object_list.inc'); ?>
    </div>

    <div id="formWrap">
        <h2>お問い合わせ内容</h2>
        <table class="fbox" summary="お問い合わせ内容" width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <th>ご希望日時<span class="must">必須</span></th>
                <td colspan="2"><div class="day"> ■日程：
                        <select name="toiawase_naiyou1" data-dispname="ご希望日時" siqatrib="toiawase_naiyou1" id="toiawase_naiyou1ID" class="chk_input chk_required">
                            <option value="">指定なし</option>
                            <?php
                            foreach ($form_cds['yoyaku_date'] as &$value) {
                                $selected = ($value[cd] == $Param['toiawase_naiyou1']) ? " selected" : "";
                                echo '<option value="' . $value[cd] . '"' . $selected . '>' . $value[nm] . '</option>';
                            }
                            ?>
                        </select>
                        <br />
                        ■お待ち合わせ時間：
                        <select name="toiawase_naiyou2" data-dispname="お待ち合わせ時間" siqatrib="toiawase_naiyou2" id="toiawase_naiyou2ID" class="chk_input chk_required">
                            <option value="">指定なし</option>
                            <?php
                            foreach ($form_cds['yoyaku_jikan'] as &$value) {
                                $selected = ($value[cd] == $Param['toiawase_naiyou2']) ? " selected" : "";
                                echo '<option value="' . $value[cd] . '"' . $selected . '>' . $value[nm] . '</option>';
                            }
                            ?>
                        </select>
                    </div>
                    <br />
                    <span class="notes">お気軽にご連絡下さい。<br>
                        ご入力いただいた内容を確認の上、ご来店いただく日時を電話かメールでご連絡させていただきます。<br>
                        ※当日や（上記日程で選択できない）直前の予約、または、予約の変更及びキャンセルの際はお手数ですが、お電話で直接お問い合わせください。<br />
                        ※第二希望、第三希望の日程がございましたら、「ご見学に関してご要望・質問など」の欄に記載してください。</span></td>
            </tr>
            <tr>
                <th>見学に関して<br />
                    ご要望・ご質問など</th>
                <td colspan="2"><textarea name="free_text" siqatrib="free_text" id="free_textID" cols="50" rows="6" class="chk_input" style="ime-mode:active;width:95%" placeholder="内容をご入力してください。" data-dispname="見学に関してご要望・ご質問など"></textarea></td>
            </tr>
        </table>
        <h2>お客様情報</h2>
        <?php include(__DIR__ . '/form_parts/kokyaku_input.inc'); ?>

        <div id="privacy">
            <p class="open">弊社の<span>プライバシーポリシー</span>をお読みいただき、すべての内容に同意のうえご登録ください。</p>
            <?php include(__DIR__ . '/form_parts/privacy_policy.inc'); ?>
            <!--/privacy-->
        </div>
        <div id="submit">
            <input type="submit" value="上記の内容で確認する" class="css_btn_class maru" onclick="myFunction();" />
            <!--/submit-->
        </div>

        <!--/formWrap-->
    </div>
</form>
<!--/inner--> 
</div>
<!--/form--> 
</div>

<?php include(__DIR__.'/../web/inc/footer.inc'); ?>
<!--/contents--> 
</div>

<!--/container-->
</div>
<?php include(__DIR__.'/../web/inc/sidebt.inc'); ?>
<!--/sidebtn--> 
</div>
</body>
</html>
