査定希望物件の種別：<?php echo $Param["kibo_type_text"];?>

築年：<?php echo $Param["chikunen_text"];?>

間取り：<?php echo $Param["madori_text"];?>

土地面積：<?php echo $Param["land_area_text"];?>

建物面積：<?php echo $Param["bld_area_text"];?>

専有面積など：<?php echo $Param["senyu_area_text"];?>

物件所在地：<?php echo $Param["shozaichi"];?>

ご希望売却価格：<?php echo ($Param["kibo_price"] != "") ? $Param["kibo_price"]."万円くらい" : "";?>

ご売却について：<?php echo $Param["douki"];?>

売却予定時期：<?php echo $Param["kibo_time"];?>

正確な査定を希望する：<?php echo $Param["correct_kibo"];?>


