＞ お客様情報
お名前　：<?php echo $Param['kokyaku_name']; ?>

ふりがな：<?php echo $Param['kokyaku_name_kn']; ?>

電話番号：<?php echo $Param['kokyaku_tel1']; ?>

メールアドレス：<?php echo $Param['mail_addr1']; ?>


ご住所：〒<?php echo $Param['zip_code']; ?>

<?php echo $Param['kokyaku_addr1']; ?>


リニュアル仲介本部への登録：<?php echo $Param['toiawase_naiyou']; ?>


当社を知ったきっかけ：
<?php echo $Param['what_baibai']; ?>


＞ログイン情報
ログインID：<?php echo $Param['mail_addr1']; ?>

パスワード：<?php echo $Param['my_page_passwd']; ?>


