<table>
<tr>
<th>エリア</th>
<td><?php echo $Param['kibo_area_name1']; ?><?php echo $err_kibo_area1; ?></td>
</tr>
<tr>
<th>物件種別</th>
<td><?php echo $Param['kibo_shubetu']; ?><?php echo $err_kibo_shubetu; ?></td>
</tr>
<tr>
<th>ご希望条件・詳細</th>
<td><?php echo $Param['kibo_biko']; ?><?php echo $err_kibo_biko; ?></td>
</tr>
<tr>
<th>弊社担当者</th>
<td>
<?php echo $Param['shimei_tantou_name']; ?><?php echo $err_shimei_tantou; ?>
</td>
</tr>
</table>
